/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as OsRouteImport } from './routes/os'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestorDashboardRouteImport } from './routes/gestor-dashboard'
import { Route as GestaoEquipeRouteImport } from './routes/gestao-equipe'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AnalistaDashboardRouteImport } from './routes/analista-dashboard'
import { Route as AdminSistemaRouteImport } from './routes/admin-sistema'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TecnicoPerfilRouteImport } from './routes/tecnico.perfil'
import { Route as TecnicoHistoricoRouteImport } from './routes/tecnico.historico'
import { Route as TecnicoDashboardRouteImport } from './routes/tecnico.dashboard'
import { Route as TecnicoOsIndexRouteImport } from './routes/tecnico.os.index'
import { Route as TecnicoOsIdRouteImport } from './routes/tecnico.os.$id'
import { Route as TecnicoOsIdRatRouteImport } from './routes/tecnico.os.$id.rat'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorDashboardRoute = GestorDashboardRouteImport.update({
  id: '/gestor-dashboard',
  path: '/gestor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoEquipeRoute = GestaoEquipeRouteImport.update({
  id: '/gestao-equipe',
  path: '/gestao-equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistaDashboardRoute = AnalistaDashboardRouteImport.update({
  id: '/analista-dashboard',
  path: '/analista-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSistemaRoute = AdminSistemaRouteImport.update({
  id: '/admin-sistema',
  path: '/admin-sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicoPerfilRoute = TecnicoPerfilRouteImport.update({
  id: '/tecnico/perfil',
  path: '/tecnico/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicoHistoricoRoute = TecnicoHistoricoRouteImport.update({
  id: '/tecnico/historico',
  path: '/tecnico/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicoDashboardRoute = TecnicoDashboardRouteImport.update({
  id: '/tecnico/dashboard',
  path: '/tecnico/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicoOsIndexRoute = TecnicoOsIndexRouteImport.update({
  id: '/tecnico/os/',
  path: '/tecnico/os/',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicoOsIdRoute = TecnicoOsIdRouteImport.update({
  id: '/tecnico/os/$id',
  path: '/tecnico/os/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicoOsIdRatRoute = TecnicoOsIdRatRouteImport.update({
  id: '/rat',
  path: '/rat',
  getParentRoute: () => TecnicoOsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-sistema': typeof AdminSistemaRoute
  '/analista-dashboard': typeof AnalistaDashboardRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRoute
  '/gestao-equipe': typeof GestaoEquipeRoute
  '/gestor-dashboard': typeof GestorDashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/os': typeof OsRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/usuarios': typeof UsuariosRoute
  '/tecnico/dashboard': typeof TecnicoDashboardRoute
  '/tecnico/historico': typeof TecnicoHistoricoRoute
  '/tecnico/perfil': typeof TecnicoPerfilRoute
  '/tecnico/os/$id': typeof TecnicoOsIdRouteWithChildren
  '/tecnico/os/': typeof TecnicoOsIndexRoute
  '/tecnico/os/$id/rat': typeof TecnicoOsIdRatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-sistema': typeof AdminSistemaRoute
  '/analista-dashboard': typeof AnalistaDashboardRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRoute
  '/gestao-equipe': typeof GestaoEquipeRoute
  '/gestor-dashboard': typeof GestorDashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/os': typeof OsRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/usuarios': typeof UsuariosRoute
  '/tecnico/dashboard': typeof TecnicoDashboardRoute
  '/tecnico/historico': typeof TecnicoHistoricoRoute
  '/tecnico/perfil': typeof TecnicoPerfilRoute
  '/tecnico/os/$id': typeof TecnicoOsIdRouteWithChildren
  '/tecnico/os': typeof TecnicoOsIndexRoute
  '/tecnico/os/$id/rat': typeof TecnicoOsIdRatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-sistema': typeof AdminSistemaRoute
  '/analista-dashboard': typeof AnalistaDashboardRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRoute
  '/gestao-equipe': typeof GestaoEquipeRoute
  '/gestor-dashboard': typeof GestorDashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/os': typeof OsRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/usuarios': typeof UsuariosRoute
  '/tecnico/dashboard': typeof TecnicoDashboardRoute
  '/tecnico/historico': typeof TecnicoHistoricoRoute
  '/tecnico/perfil': typeof TecnicoPerfilRoute
  '/tecnico/os/$id': typeof TecnicoOsIdRouteWithChildren
  '/tecnico/os/': typeof TecnicoOsIndexRoute
  '/tecnico/os/$id/rat': typeof TecnicoOsIdRatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-sistema'
    | '/analista-dashboard'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipe'
    | '/estoque'
    | '/gestao-equipe'
    | '/gestor-dashboard'
    | '/login'
    | '/logs'
    | '/os'
    | '/planos'
    | '/privacidade'
    | '/termos-de-uso'
    | '/usuarios'
    | '/tecnico/dashboard'
    | '/tecnico/historico'
    | '/tecnico/perfil'
    | '/tecnico/os/$id'
    | '/tecnico/os/'
    | '/tecnico/os/$id/rat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-sistema'
    | '/analista-dashboard'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipe'
    | '/estoque'
    | '/gestao-equipe'
    | '/gestor-dashboard'
    | '/login'
    | '/logs'
    | '/os'
    | '/planos'
    | '/privacidade'
    | '/termos-de-uso'
    | '/usuarios'
    | '/tecnico/dashboard'
    | '/tecnico/historico'
    | '/tecnico/perfil'
    | '/tecnico/os/$id'
    | '/tecnico/os'
    | '/tecnico/os/$id/rat'
  id:
    | '__root__'
    | '/'
    | '/admin-sistema'
    | '/analista-dashboard'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipe'
    | '/estoque'
    | '/gestao-equipe'
    | '/gestor-dashboard'
    | '/login'
    | '/logs'
    | '/os'
    | '/planos'
    | '/privacidade'
    | '/termos-de-uso'
    | '/usuarios'
    | '/tecnico/dashboard'
    | '/tecnico/historico'
    | '/tecnico/perfil'
    | '/tecnico/os/$id'
    | '/tecnico/os/'
    | '/tecnico/os/$id/rat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSistemaRoute: typeof AdminSistemaRoute
  AnalistaDashboardRoute: typeof AnalistaDashboardRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EquipeRoute: typeof EquipeRoute
  EstoqueRoute: typeof EstoqueRoute
  GestaoEquipeRoute: typeof GestaoEquipeRoute
  GestorDashboardRoute: typeof GestorDashboardRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  OsRoute: typeof OsRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  UsuariosRoute: typeof UsuariosRoute
  TecnicoDashboardRoute: typeof TecnicoDashboardRoute
  TecnicoHistoricoRoute: typeof TecnicoHistoricoRoute
  TecnicoPerfilRoute: typeof TecnicoPerfilRoute
  TecnicoOsIdRoute: typeof TecnicoOsIdRouteWithChildren
  TecnicoOsIndexRoute: typeof TecnicoOsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor-dashboard': {
      id: '/gestor-dashboard'
      path: '/gestor-dashboard'
      fullPath: '/gestor-dashboard'
      preLoaderRoute: typeof GestorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-equipe': {
      id: '/gestao-equipe'
      path: '/gestao-equipe'
      fullPath: '/gestao-equipe'
      preLoaderRoute: typeof GestaoEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analista-dashboard': {
      id: '/analista-dashboard'
      path: '/analista-dashboard'
      fullPath: '/analista-dashboard'
      preLoaderRoute: typeof AnalistaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-sistema': {
      id: '/admin-sistema'
      path: '/admin-sistema'
      fullPath: '/admin-sistema'
      preLoaderRoute: typeof AdminSistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnico/perfil': {
      id: '/tecnico/perfil'
      path: '/tecnico/perfil'
      fullPath: '/tecnico/perfil'
      preLoaderRoute: typeof TecnicoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnico/historico': {
      id: '/tecnico/historico'
      path: '/tecnico/historico'
      fullPath: '/tecnico/historico'
      preLoaderRoute: typeof TecnicoHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnico/dashboard': {
      id: '/tecnico/dashboard'
      path: '/tecnico/dashboard'
      fullPath: '/tecnico/dashboard'
      preLoaderRoute: typeof TecnicoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnico/os/': {
      id: '/tecnico/os/'
      path: '/tecnico/os'
      fullPath: '/tecnico/os/'
      preLoaderRoute: typeof TecnicoOsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnico/os/$id': {
      id: '/tecnico/os/$id'
      path: '/tecnico/os/$id'
      fullPath: '/tecnico/os/$id'
      preLoaderRoute: typeof TecnicoOsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnico/os/$id/rat': {
      id: '/tecnico/os/$id/rat'
      path: '/rat'
      fullPath: '/tecnico/os/$id/rat'
      preLoaderRoute: typeof TecnicoOsIdRatRouteImport
      parentRoute: typeof TecnicoOsIdRoute
    }
  }
}

interface TecnicoOsIdRouteChildren {
  TecnicoOsIdRatRoute: typeof TecnicoOsIdRatRoute
}

const TecnicoOsIdRouteChildren: TecnicoOsIdRouteChildren = {
  TecnicoOsIdRatRoute: TecnicoOsIdRatRoute,
}

const TecnicoOsIdRouteWithChildren = TecnicoOsIdRoute._addFileChildren(
  TecnicoOsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSistemaRoute: AdminSistemaRoute,
  AnalistaDashboardRoute: AnalistaDashboardRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EquipeRoute: EquipeRoute,
  EstoqueRoute: EstoqueRoute,
  GestaoEquipeRoute: GestaoEquipeRoute,
  GestorDashboardRoute: GestorDashboardRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  OsRoute: OsRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  UsuariosRoute: UsuariosRoute,
  TecnicoDashboardRoute: TecnicoDashboardRoute,
  TecnicoHistoricoRoute: TecnicoHistoricoRoute,
  TecnicoPerfilRoute: TecnicoPerfilRoute,
  TecnicoOsIdRoute: TecnicoOsIdRouteWithChildren,
  TecnicoOsIndexRoute: TecnicoOsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
